#ifndef BASE_DISSECTOR_COMPAT_H
#define BASE_DISSECTOR_COMPAT_H

#include <base/system.h>

#include <engine/shared/network.h>
#include <game/version.h>

#include <engine/shared/protocol.h>
#if __has_include(<game/generated/protocol.h>)
#include <game/generated/protocol.h>
#endif
#if __has_include(<game/generated/protocol7.h>)
#include <game/generated/protocol7.h>
#endif
#if __has_include(<game/generated/protocolglue.h>)
#include <game/generated/protocolglue.h>
#endif

#ifndef int64
typedef long long int64;
#endif


void init_compat();

#define _MAX_NETOBJSIZES 64

// missing 0.7 constant -> assume ddnet or any other 0.6 codebase
#ifndef PREV_CLIENT_VERSION
    #define _NET_PACKETHEADERSIZE_CONNLESS 9
	#define _NET_PACKETHEADERSIZE 7

	#define _NETMSG_NULL 0
	#define _NETMSG_SERVERINFO 4
	#define _NETMSG_RCON_AUTH_ON 11
	#define _NETMSG_RCON_AUTH_OFF 12

	#define _NETMSG_MAPLIST_ENTRY_ADD 29
	#define _NETMSG_MAPLIST_ENTRY_REM 30

	#define _NETOBJ_INVALID protocol7::NETOBJ_INVALID
	#define _NETOBJTYPE_PLAYERINPUT protocol7::NETOBJTYPE_PLAYERINPUT
	#define _NETOBJTYPE_PROJECTILE protocol7::NETOBJTYPE_PROJECTILE
	#define _NETOBJTYPE_LASER protocol7::NETOBJTYPE_LASER
	#define _NETOBJTYPE_PICKUP protocol7::NETOBJTYPE_PICKUP
	#define _NETOBJTYPE_FLAG protocol7::NETOBJTYPE_FLAG
	#define _NETOBJTYPE_GAMEDATA protocol7::NETOBJTYPE_GAMEDATA
	#define _NETOBJTYPE_GAMEDATATEAM protocol7::NETOBJTYPE_GAMEDATATEAM
	#define _NETOBJTYPE_GAMEDATAFLAG protocol7::NETOBJTYPE_GAMEDATAFLAG
	#define _NETOBJTYPE_CHARACTERCORE protocol7::NETOBJTYPE_CHARACTERCORE
	#define _NETOBJTYPE_CHARACTER protocol7::NETOBJTYPE_CHARACTER
	#define _NETOBJTYPE_PLAYERINFO protocol7::NETOBJTYPE_PLAYERINFO
	#define _NETOBJTYPE_SPECTATORINFO protocol7::NETOBJTYPE_SPECTATORINFO
	#define _NETOBJTYPE_DE_CLIENTINFO protocol7::NETOBJTYPE_DE_CLIENTINFO
	#define _NETOBJTYPE_DE_GAMEINFO protocol7::NETOBJTYPE_DE_GAMEINFO
	#define _NETOBJTYPE_DE_TUNEPARAMS protocol7::NETOBJTYPE_DE_TUNEPARAMS
	#define _NETEVENTTYPE_COMMON protocol7::NETEVENTTYPE_COMMON
	#define _NETEVENTTYPE_EXPLOSION protocol7::NETEVENTTYPE_EXPLOSION
	#define _NETEVENTTYPE_SPAWN protocol7::NETEVENTTYPE_SPAWN
	#define _NETEVENTTYPE_HAMMERHIT protocol7::NETEVENTTYPE_HAMMERHIT
	#define _NETEVENTTYPE_DEATH protocol7::NETEVENTTYPE_DEATH
	#define _NETEVENTTYPE_SOUNDWORLD protocol7::NETEVENTTYPE_SOUNDWORLD
	#define _NETEVENTTYPE_DAMAGE protocol7::NETEVENTTYPE_DAMAGE
	#define _NETOBJTYPE_PLAYERINFORACE protocol7::NETOBJTYPE_PLAYERINFORACE
	#define _NETOBJTYPE_GAMEDATARACE protocol7::NETOBJTYPE_GAMEDATARACE

    #define _NET_CONNSTATE_TOKEN 999
    #define _NET_CTRLMSG_TOKEN 999

    extern short _gs_aItemSizes[_MAX_NETOBJSIZES];

    #define _PROTOCOL_VERSION_6
#else // 0.7
    #define _NET_PACKETHEADERSIZE_CONNLESS NET_PACKETHEADERSIZE_CONNLESS
	#define _NET_PACKETHEADERSIZE NET_PACKETHEADERSIZE

    #define _NETMSG_NULL NETMSG_NULL
    #define _NETMSG_SERVERINFO NETMSG_SERVERINFO
    #define _NETMSG_RCON_AUTH_ON NETMSG_RCON_AUTH_ON
    #define _NETMSG_RCON_AUTH_OFF NETMSG_RCON_AUTH_OFF
    #define _NETMSG_MAPLIST_ENTRY_ADD NETMSG_MAPLIST_ENTRY_ADD
    #define _NETMSG_MAPLIST_ENTRY_REM NETMSG_MAPLIST_ENTRY_REM

    #define _NETOBJ_INVALID NETOBJ_INVALID
    #define _NETOBJTYPE_PLAYERINPUT NETOBJTYPE_PLAYERINPUT
    #define _NETOBJTYPE_PROJECTILE NETOBJTYPE_PROJECTILE
    #define _NETOBJTYPE_LASER NETOBJTYPE_LASER
    #define _NETOBJTYPE_PICKUP NETOBJTYPE_PICKUP
    #define _NETOBJTYPE_FLAG NETOBJTYPE_FLAG
    #define _NETOBJTYPE_GAMEDATA NETOBJTYPE_GAMEDATA
    #define _NETOBJTYPE_GAMEDATATEAM NETOBJTYPE_GAMEDATATEAM
    #define _NETOBJTYPE_GAMEDATAFLAG NETOBJTYPE_GAMEDATAFLAG
    #define _NETOBJTYPE_CHARACTERCORE NETOBJTYPE_CHARACTERCORE
    #define _NETOBJTYPE_CHARACTER NETOBJTYPE_CHARACTER
    #define _NETOBJTYPE_PLAYERINFO NETOBJTYPE_PLAYERINFO
    #define _NETOBJTYPE_SPECTATORINFO NETOBJTYPE_SPECTATORINFO
    #define _NETOBJTYPE_DE_CLIENTINFO NETOBJTYPE_DE_CLIENTINFO
    #define _NETOBJTYPE_DE_GAMEINFO NETOBJTYPE_DE_GAMEINFO
    #define _NETOBJTYPE_DE_TUNEPARAMS NETOBJTYPE_DE_TUNEPARAMS
    #define _NETEVENTTYPE_COMMON NETEVENTTYPE_COMMON
    #define _NETEVENTTYPE_EXPLOSION NETEVENTTYPE_EXPLOSION
    #define _NETEVENTTYPE_SPAWN NETEVENTTYPE_SPAWN
    #define _NETEVENTTYPE_HAMMERHIT NETEVENTTYPE_HAMMERHIT
    #define _NETEVENTTYPE_DEATH NETEVENTTYPE_DEATH
    #define _NETEVENTTYPE_SOUNDWORLD NETEVENTTYPE_SOUNDWORLD
    #define _NETEVENTTYPE_DAMAGE NETEVENTTYPE_DAMAGE
    #define _NETOBJTYPE_PLAYERINFORACE NETOBJTYPE_PLAYERINFORACE
    #define _NETOBJTYPE_GAMEDATARACE NETOBJTYPE_GAMEDATARACE

    #define _NET_CONNSTATE_TOKEN NET_CONNSTATE_TOKEN
    #define _NET_CTRLMSG_TOKEN NET_CTRLMSG_TOKEN

    #define _PROTOCOL_VERSION_7
#endif


#endif
