#ifndef BASE_DISSECTOR_COMPAT_H
#define BASE_DISSECTOR_COMPAT_H


#include <engine/shared/network.h>
#include <game/version.h>

#ifndef int64
typedef long long int64;
#endif

// missing 0.7 constant -> assume ddnet or any other 0.6 codebase
#ifndef PREV_CLIENT_VERSION
    #define _NET_PACKETHEADERSIZE_CONNLESS 9
	#define _NET_PACKETHEADERSIZE 7

	#define _NETMSG_NULL 0
	#define _NETMSG_SERVERINFO 4
	#define _NETMSG_RCON_AUTH_ON 11
	#define _NETMSG_RCON_AUTH_OFF 12

	#define _NETMSG_MAPLIST_ENTRY_ADD 29
	#define _NETMSG_MAPLIST_ENTRY_REM 30

    #define _NETOBJ_INVALID 0
    #define _NETOBJTYPE_GAMEDATATEAM 7
    #define _NETOBJTYPE_GAMEDATAFLAG 8
    #define _NETOBJTYPE_DE_CLIENTINFO 13
    #define _NETOBJTYPE_DE_GAMEINFO 14
    #define _NETOBJTYPE_DE_TUNEPARAMS 15
    #define _NETEVENTTYPE_DAMAGE 22
    #define _NETOBJTYPE_PLAYERINFORACE 23
    #define _NETOBJTYPE_GAMEDATARACE 24

    #define _PROTOCOL_VERSION_6
#else // 0.7
    #define _NET_PACKETHEADERSIZE_CONNLESS NET_PACKETHEADERSIZE_CONNLESS
	#define _NET_PACKETHEADERSIZE NET_PACKETHEADERSIZE

    #define _NETMSG_NULL NETMSG_NULL
    #define _NETMSG_SERVERINFO NETMSG_SERVERINFO
    #define _NETMSG_RCON_AUTH_ON NETMSG_RCON_AUTH_ON
    #define _NETMSG_RCON_AUTH_OFF NETMSG_RCON_AUTH_OFF
    #define _NETMSG_MAPLIST_ENTRY_ADD NETMSG_MAPLIST_ENTRY_ADD
    #define _NETMSG_MAPLIST_ENTRY_REM NETMSG_MAPLIST_ENTRY_REM

    #define _NETOBJ_INVALID NETOBJ_INVALID
    #define _NETOBJTYPE_GAMEDATATEAM NETOBJTYPE_GAMEDATATEAM
    #define _NETOBJTYPE_GAMEDATAFLAG NETOBJTYPE_GAMEDATAFLAG
    #define _NETOBJTYPE_DE_CLIENTINFO NETOBJTYPE_DE_CLIENTINFO
    #define _NETOBJTYPE_DE_GAMEINFO NETOBJTYPE_DE_GAMEINFO
    #define _NETOBJTYPE_DE_TUNEPARAMS NETOBJTYPE_DE_TUNEPARAMS
    #define _NETEVENTTYPE_DAMAGE NETEVENTTYPE_DAMAGE
    #define _NETOBJTYPE_PLAYERINFORACE NETOBJTYPE_PLAYERINFORACE
    #define _NETOBJTYPE_GAMEDATARACE NETOBJTYPE_GAMEDATARACE

    #define _PROTOCOL_VERSION_7
#endif


#endif
