name: Check style

on:
  push:
    branches-ignore:
      - master
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp
  pull_request:

jobs:
  check-style:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install clang-format shellcheck pkg-config cmake libfreetype6-dev libsdl2-dev python3-clang -y
    - name: Check clang-format
      run: clang-format -version
    - name: Check fix_style
      run: scripts/fix_style.py --dry-run || true
